### ISSUE TITLE
install.sh for init use and pip3

### ISSUE THREAD

**Issue by aserowy** [siduck76/neovim-dots#13]
Hi,

first things first: you are awesome! I think i found my default conf.
While installing on a fresh ubuntu, i had to change your install.sh that the install was running cleanly.

Can i pr you my minimal changes?

Kind regards and thx for your work
Alexander

**Comment by siduck76** [comment]
yeah of course!

**Comment by aserowy** [comment]
opened pr #14

**Comment by siduck76** [comment]
It has been merged

**Comment by aserowy** [comment]
#14 merged :)

👍
