### ISSUE TITLE
added kabouzeid/nvim-lspinstall

### ISSUE THREAD

**Issue by aserowy** [siduck76/neovim-dots#16]
hey there :)

ive added kabouzeid/nvim-lspinstall in my fork and reworked automatic installation of packer. Thus, the install.sh shrunk to pieces and lsp installs and keybindings are more dynamic.
If you are interested, ill pr you.

Kind regards
Alexander

**Comment by siduck76** [comment]
Thanks for adding the automatic installation of packer! lspInstall still doesnt support all the languages so I think we should put it on hold for a while and I'd want some languages having lsp support by default like html , css , js  and those default languages having treesitter parsers installed too . We'll make some changes soon like for example install.sh would print the list of all languages currently supported by lspconfig and prompt the user to select their languages , which will then have treesitter parsers and lsp servers/configs installed for those languages.

**Comment by aserowy** [comment]
@siduck76 
i changed tree sitter a little bit, thus all moderated parser are initialized (little overhead at first start of nvim).
https://github.com/aserowy/neovim-dots/blob/main/lua/treesitter/lua.lua

Beyond the languages already supported, you can add custom lsps as well with this extension: https://github.com/kabouzeid/nvim-lspinstall#custom-installer

Thus, you can install lsps on startup without calling node and stuff and add customs as you wish.

Kind regards

**Comment by siduck76** [comment]
send the PR tomorrow :)

**Comment by aserowy** [comment]
ok, in my timezone it is tomorrow (8am) :D

i filed pr #23

**Comment by aserowy** [comment]
closed pr, because requirements could not be met.

kind regards
alexander

**Comment by siduck76** [comment]
@aserowy We need to wait until nvim-Lspinstall supports more languages and as for now it doesnt support pythong lsp servers , it supports pyright which doesnt work as mentioned.

![image](https://user-images.githubusercontent.com/59060246/114259967-755a0780-99ef-11eb-82f7-91bafaf6e88e.png)

**Comment by siduck76** [comment]
> @aserowy We need to wait until nvim-Lspinstall supports more languages and as for now it doesnt support pythong lsp servers , it supports pyright which doesnt work as mentioned.
> 
> ![image](https://user-images.githubusercontent.com/59060246/114259967-755a0780-99ef-11eb-82f7-91bafaf6e88e.png)

I think it would be easier to add some changes in the install.sh , to add a set of default languages ( which will install lsp servers and tree-sitter parsers for those ) and prompt the user for selecting the lsp servers only they want :)
