### ISSUE TITLE
Allow users to change the shell

### ISSUE THREAD

**Issue by marvelman3284** [siduck76/neovim-dots#18]
When I had first installed the configs I had to manually change my shell from bash to zsh in `mappings/lua.lua`. I would try to implement this feature myself but I don't know enough shell or lua to do it.

**Comment by siduck76** [comment]
I dont think lua is required for this , only some basic shell with sed to replace stuffs would be enough , I'll add it tomorrow .

**Comment by siduck76** [comment]
added it 3865b28
