### ISSUE TITLE
Error with the new colors/install.sh

### ISSUE THREAD

**Issue by marvelman3284** [siduck76/neovim-dots#19]
It had been a few days since I had pulled from the repo and after I had I was greeted with this on startup of nvim:
![image](https://user-images.githubusercontent.com/58921302/113645931-cbc4f000-9655-11eb-8100-30b8e8f56bdb.png)
Once again I am using Arch Linux.

**Comment by siduck76** [comment]
:PackerInstall after running the install.sh script

**Comment by marvelman3284** [comment]
Fixed
