### ISSUE TITLE
Color theme is totally blue

### ISSUE THREAD

**Issue by ShivamJoker** [siduck76/neovim-dots#2]
![image](https://user-images.githubusercontent.com/23727670/111281870-676ccd00-8663-11eb-8af5-6312720d68f1.png)

I followed the exact instructions I am using macos.
I installed nvim using brew

**Comment by siduck76** [comment]
did your old config ( with any colorscheme set ) work?

**Comment by ShivamJoker** [comment]
I was using one-dark and it was working perfect
You can find the files here - https://github.com/ShivamJoker/Nvim-config

**Comment by siduck76** [comment]
you sure you're using neovim nightly or 0.5?

**Comment by ShivamJoker** [comment]
Okay the issue was with Mac Terminal, it didn't support 24 bit color so I was facing the issue.
Thanks for the config though

**Comment by rashadphil** [comment]
I'm getting the same issue in my Mac Terminal. How did you fix this?

**Comment by ShivamJoker** [comment]
You can simply install iTerm or use the one dark theme from my config
