### ISSUE TITLE
code suggestions not working

### ISSUE THREAD

**Issue by Alex-crypto-tech** [siduck76/neovim-dots#20]
Hi, love from Germany :)

I cloned your setup and code suggestion for .lua files worked out of the box.
I tried adding the 'require.pyls......" line which you mentioned in README for python, but it did not work.

Kindly help!

Thanks again

**Comment by siduck76** [comment]
@Alex-crypto-tech  Did you include pyls in lspconfig ? 
![image](https://user-images.githubusercontent.com/59060246/113653056-b0d49900-96b2-11eb-9ce9-8bacc2970be3.png)

I dont code in python , tested a file and autocompletions work 
![image](https://user-images.githubusercontent.com/59060246/113653089-c6e25980-96b2-11eb-82bf-1a771f4b491b.png)

**Comment by marvelman3284** [comment]
@Alex-crypto-tech 
You shouldn't need to add that line because the python language server comes bundled with the configs. I would recommend pull from master to get the latest code then re-running `install.sh`.

**Comment by Alex-crypto-tech** [comment]
Actually I had cloned the repo yesterday. 
I tried doing it again, and now it is working fine.
Thanks guys!
Y'all rock :)
