### ISSUE TITLE
Which Font Do You Use

### ISSUE THREAD

**Issue by usdogu** [siduck76/neovim-dots#22]
I am on kitty terminal with Fira Code Nerd Font but I tried a few fonts too all of them have same problem the icons is not displayed. can you check the attached screenshots?
![2021-04-06_08-43](https://user-images.githubusercontent.com/73913444/113664415-60f6d180-96b4-11eb-801e-81f7a95ec9db.png)
![2021-04-06_08-43_1](https://user-images.githubusercontent.com/73913444/113664418-618f6800-96b4-11eb-8a7b-df00ee797f7b.png)
![2021-04-06_08-44](https://user-images.githubusercontent.com/73913444/113664419-6227fe80-96b4-11eb-8e24-27e575f1cd14.png)

**Comment by siduck76** [comment]
I use JetbrainsMono NerdFont Medium on my custom st terminal https://github.com/siduck76/st , 
I load fonts and colors with xresources https://github.com/siduck76/dotfiles/blob/master/thinkpad/.Xresources

**Comment by usdogu** [comment]
thanks a lot it worked, I am closing the issue
