### ISSUE TITLE
colorscheme issue

### ISSUE THREAD

**Issue by laughing-stock** [siduck76/neovim-dots#25]
I think the line numbers are too dark. Also, comment lines are also too dark.
One can hardly view them.

Perhaps you might wanna replace them with a bit lighter ones.

**Comment by siduck76** [comment]
cmd "hi LineNr guifg=#42464e guibg=NONE"
cmd "hi Comment guifg=#42464e" 

@laughing-stock

**Comment by siduck76** [comment]
> I think the line numbers are too dark. Also, comment lines are also too dark.
> One can hardly view them.
> 
> Perhaps you might wanna replace them with a bit lighter ones.

**Comment by siduck76** [comment]
c62616cfee4c092968df8cd0097c7d46ef468e04 fixes it
