### ISSUE TITLE
Should Telescope media_files work out of the box?

### ISSUE THREAD

**Issue by meaz** [siduck76/neovim-dots#26]
I have used your script to deploy your setup. It works fine, except for Telescope media_files that doesn't show anything. It is like if the folder was empty. Are there any dependencies to be installed in order to display images in terminal?

**Comment by siduck76** [comment]
@meaz  oh sorry I forgot to mention some things ,  you need ueberzug installed .

**Comment by siduck76** [comment]
> @meaz oh sorry I forgot to mention some things , you need ueberzug ,  ripgrep nstalled .

**Comment by meaz** [comment]
thanks! Should I close this ticket or you'll do it when readme is updated?

**Comment by meaz** [comment]
thanks!

**Comment by bjesus** [comment]
Sorry to bring this back to life, but is there anything else that's needed? I'm on Linux, I have `rg`  and `ueberzug` installed, but still see no image preview. Tried both with Alacritty and Kitty. Do I need anything else?

**Comment by siduck76** [comment]
> Sorry to bring this back to life, but is there anything else that's needed? I'm on Linux, I have `rg` and `ueberzug` installed, but still see no image preview. Tried both with Alacritty and Kitty. Do I need anything else?

I dont think so , could you show me what does telescope preview with image files?

**Comment by bjesus** [comment]
Just empty:

![screenshot_2021-08-22_10-12-43_218380489](https://user-images.githubusercontent.com/55081/130347480-c59c0b5a-fc35-48d9-a9a1-6f0b8c79d804.png)

**Comment by prurph** [comment]
Also seeing the same issue.

**Comment by siduck76** [comment]
> Also seeing the same issue.

@bjesus it will work on linux only and you need ueberzug working + ripgrep instead too. Test ueberzug in ranger first to check whether it's working on your system.

**Comment by prurph** [comment]
I figured out my issue: ueberzug does not work on Wayland, and I'm using swaywm. @bjesus any chance this is your problem as well?

I was able to verify this by installing ranger, setting [`preview_images_method`](https://github.com/ranger/ranger/wiki/Official-user-guide#image-previews) to ueberzug, and noticed there were no images. When I set it to `kitty` (I'm using kitty term), the images worked inside of ranger. I should also note trying to use kitty for preview images from inside of tmux caused ranger to hang.

@siduck76 sorry for the confusion. Looks like this is a Wayland/ueberzug issue and not an NvChad or a Telescope one.

**Comment by bjesus** [comment]
Got it. Also using Wayland & Sway here, I guess that's the reason. Will disable telescope-media for now. Thank you 🙏

**Comment by siduck** [comment]
@bjesus sorry for the late reply but st + ueberzug on wayland ( knowing that xwayland is running in the bg) , this can still work. My brother uses wayfire and my st build, ueberzug did work. https://github.com/siduck76/st

**Comment by siduck** [comment]
@bjesus @prurph  sorry for the late reply but st + ueberzug on wayland ( knowing that xwayland is running in the bg) , this can still work. My brother uses wayfire and my st build, ueberzug did work. https://github.com/siduck76/st

**Comment by bjesus** [comment]
Interesting, thanks for updating! I try to avoid Xwayland and don't actually have it installed, but maybe I'll give it shot later :) Thanks!
