### ISSUE TITLE
Packer install

### ISSUE THREAD

**Issue by 7ze** [siduck76/neovim-dots#29]
Consider this more of a doubt, than an issue.

 I was going through your neovim dots ( I love it ) and in pluginsList, you check if packer is already installed with `pcall` like this:
`local packer_exists = pcall(vim.cmd, [[packadd packer.nvim]])`

I was wondering why you did this and if the variable `packer_exists` holds any significance. ( you didn't use it anywhere after you declared it, if I am not mistaken )

Since we install packer into `packer/start` anyway ( like in the install script ), shouldn't vim automatically load it for us at the start, without us having to say `packadd packer.nvim` ?

And I am also confused as to why you lazy load packer here:
`use {"wbthomason/packer.nvim", opt = true}`

And if packer is not installed in `site/pack`, wouldn't neovim throw an error regardless of the pcall check, given that packer cannot be loaded?

**Comment by 7ze** [comment]
Bear with me,  I am just a noob, btw. 
Your neovim config has been a great inspiration for me.

**Comment by siduck76** [comment]
@7ze  I have the lazy loading included , so as to update packer and it has opt set as true so I have to use packadd packer.nvim or I'll get errors . 

![image](https://user-images.githubusercontent.com/59060246/115439547-539d2380-a22c-11eb-87ba-6bcc06e9d82d.png)

**Comment by siduck76** [comment]
> Bear with me, I am just a noob, btw.
> Your neovim config has been a great inspiration for me.

No issues , Im a noob myself!

**Comment by 7ze** [comment]
> @7ze I have the lazy loading included , so as to update packer and it has opt set as true so I have to use packadd packer.nvim to load packer.nvim , read the below config .
> 
> ![image](https://user-images.githubusercontent.com/59060246/115439547-539d2380-a22c-11eb-87ba-6bcc06e9d82d.png)

Ah yes, it's mentioned in the packer documentation. 

But for other plugins like nvim-compe configuration in `lua/compe/lua.lua`, you  still add `vim.cmd [[packadd nvim-compe]]`, this even when they are not configured as opt. Is that a design choice?

As always, thanks for taking the time to answer my questions.

**Comment by siduck76** [comment]
I think yes , its necessary to run packer.nvim before running compe's config first , I've seen it in many configs :

example : https://github.com/elianiva/dotfiles/blob/master/nvim/.config/nvim/lua/plugins/_compe.lua

**Comment by 7ze** [comment]
I think he had to manually `packadd nvim-compe` because he configured nvim-compe as a opt plugin here :
https://github.com/elianiva/dotfiles/blob/master/nvim/.config/nvim/lua/plugins/_packer.lua

(from line 70)
```
 -- Auto completion plugin for nvim written in Lua.
    use {
      "~/repos/nvim-compe",
      opt = true,
      requires = {
        -- Snippet plugin for vim/nvim that supports LSP/VSCode's snippet
        -- format. Only used for LSP completion that needs snippet and todo stuff
        { "L3MON4D3/LuaSnip" },
      },
    }
```

**Comment by siduck76** [comment]
@7ze Yeah , Ive configured packer.nvim as opt plugin so I used vim.cmd [[packadd nvim-compe]]

**Comment by 7ze** [comment]
@siduck76 

As far as I understand, you only need to use `vim.cmd [[packadd foo]]` to load a plugin if that plugin _itself_, is installed in `pack/*/opt` i.e to say if you did something like this `use {'some_repo/foo', opt = true}`.
( Check out vim's documentation - `:h packages` )

So if you install a plugin using packer like this:
`use 'some_repo/foo'` 

then you don't need to manually do `vim.cmd [[packadd foo]]` to load the plugin, since it should be installed in `pack/*/start` which vim should auto-load.

**Comment by siduck76** [comment]
@7ze yeah Im aware , I had packer.nvim configured as opt so I had to packadd it.

**Comment by 7ze** [comment]
ah, so it doesn't matter then? I see, I am confused. So if we have packer configured as opt, then we have to pack add all the plugins manually regardless of how we configure each plugin.

Thanks for reaching out once again. Closing this issue.
