### ISSUE TITLE
Autocompletion doesn't work properly and also there are no language definition

### ISSUE THREAD

**Issue by ShivamJoker** [siduck76/neovim-dots#3]
![image](https://user-images.githubusercontent.com/23727670/111337367-09a8a700-869c-11eb-9b53-a1c9b3561c7f.png)

I came around few plugins but I don't have that much idea on integrating everything together

https://github.com/glepnir/lspsaga.nvim
https://github.com/nvim-lua/completion-nvim

**Comment by siduck76** [comment]
Oh unfortunately , I dont use completion-nvim and lspsaga.nvim . I use nvim-compe . did you try the autocompletition with nvim-compe ?

**Comment by ShivamJoker** [comment]
I have your configuration, nothing changed it does auto complete but when I hit enter it only adds the first word.

No I don't know how to setup those plugins 😅

**Comment by siduck76** [comment]
Ah dont use enter for the completion! use space key instead . pressing enter on a completion item willl get the cursor to the new line . and Also I'll implement the definition on hover later , got exams these days >:(

**Comment by ShivamJoker** [comment]
Space key ? It just adds an space 🙄 I select the line then I press enter.

Shouldn't this be default ?

**Comment by siduck76** [comment]
> Space key ? It just adds an space  I select the line then I press enter. Shouldn't this be default ?

yeah I'll try to fix it , https://share.vidyard.com/watch/CoR9q9gUNE9QXFBYWTcFMb? , for now I just use space key

**Comment by ShivamJoker** [comment]
It's not same here it adds a space rather than completion 
See https://photos.app.goo.gl/x4BRYbBpXr8kB7E47

**Comment by siduck76** [comment]
yea it doesnt work well , font names with strings do work rather than selecting the ones starting with hyphen 

See https://photos.app.goo.gl/1japjrixirB1wBgX8

**Comment by ShivamJoker** [comment]
I guess it's very buggy we should probably report this, the space only works for one word.
 And sometimes it completely stops working 😑

**Comment by siduck76** [comment]
autocompletion works well for me all the time , its just that it works weird when you try to use local-fonts in font-family I think , and also for the enter key thing , its not available by default in nvim-compe so I have to add some functions and mappings , I got it here 
https://github.com/kraftwerk28/dotfiles/blob/master/.config/nvim/init.vim#L197-L219 ( have to convert it in lua code ) and as Im still new to lua , it'll take some time to fix it with my exams going on :p

**Comment by ShivamJoker** [comment]
Will try once everything becomes stable
I switched back to coc

**Comment by jordanlacopo** [comment]
Just replace with this if you want tab to auto complete

local t = function(str)
  return vim.api.nvim_replace_termcodes(str, true, true, true)
end

local check_back_space = function()
    local col = vim.fn.col('.') - 1
    if col == 0 or vim.fn.getline('.'):sub(col, col):match('%s') then
        return true
    else
        return false
    end
end

-- Use (s-)tab to:
--- move to prev/next item in completion menuone
--- jump to prev/next snippet's placeholder
_G.tab_complete = function()
  if vim.fn.pumvisible() == 1 then
    return t "<C-n>"
  elseif vim.fn.call("vsnip#available", {1}) == 1 then
    return t "<Plug>(vsnip-expand-or-jump)"
  elseif check_back_space() then
    return t "<Tab>"
  else
    return vim.fn['compe#complete']()
  end
end
_G.s_tab_complete = function()
  if vim.fn.pumvisible() == 1 then
    return t "<C-p>"
  elseif vim.fn.call("vsnip#jumpable", {-1}) == 1 then
    return t "<Plug>(vsnip-jump-prev)"
  else
    return t "<S-Tab>"
  end
end

vim.api.nvim_set_keymap("i", "<Tab>", "v:lua.tab_complete()", {expr = true})
vim.api.nvim_set_keymap("s", "<Tab>", "v:lua.tab_complete()", {expr = true})
vim.api.nvim_set_keymap("i", "<S-Tab>", "v:lua.s_tab_complete()", {expr = true})
vim.api.nvim_set_keymap("s", "<S-Tab>", "v:lua.s_tab_complete()", {expr = true})
