### ISSUE TITLE
PackerInstall isn't installed

### ISSUE THREAD

**Issue by mTvare6** [siduck76/neovim-dots#30]
I ran ```git clone https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim``` but still PackerInstall doesn't work

**Comment by siduck76** [comment]
try 
git clone https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim

**Comment by mTvare6** [comment]
Still doesn't work :/ (video)[https://transfer.sh/6m73z/Screen%20Recording%202021-04-24%20at%205.56.49%20PM.mov]

**Comment by siduck76** [comment]
@mTvare6 show the output of ls .local/share/nvim/site/pack

**Comment by mTvare6** [comment]
packer

**Comment by siduck76** [comment]
Looks like packer is installed , I wonder why doesnt :PackerInstall work :(

**Comment by mTvare6** [comment]
I was using NVIM 0.4.4
