### ISSUE TITLE
Auto Save Not Working

### ISSUE THREAD

**Issue by marvelman3284** [siduck76/neovim-dots#32]
After not pulling from master for a long time today I finally did. On nvim start up after pulling I was greeted with an error about the zen plugin, but I didn't think to screenshot it. After doing some editing I found out that my files were no long autosaving. I am not sure if the zen error message and this are linked but I tried removing truezen from the pluginslist and that did not fix my error.

### Screenshots
![image](https://user-images.githubusercontent.com/58921302/116025871-7ad66500-a61f-11eb-8d2d-c272cd8daeb6.png)
_Before changes_
![image](https://user-images.githubusercontent.com/58921302/116025906-8de93500-a61f-11eb-95ef-b5ca83949134.png)
_Making changes_
![image](https://user-images.githubusercontent.com/58921302/116025926-99d4f700-a61f-11eb-8496-d82ef2925819.png)
_Exiting out of edit mode after finishing changes_

### Notes
As you can see in the screenshots the little dot on the file name does not go away after hitting <kbd> esc </kbd> to return to normal mode. 
#### Sys info
I am running arch linux on 5.11.15
Neovim is neovim night from the [aur](https://aur.archlinux.org/packages/neovim-nightly-bin/).

If there is any other info that is needed let me to and i will provide it as soon as possible

**Comment by siduck76** [comment]
@marvelman3284 auto_save is disabled by default , set g.auto_save = 1 in init.lua
![image](https://user-images.githubusercontent.com/59060246/116027307-21e3ec80-a672-11eb-82cf-16c74590ba99.png)

**Comment by marvelman3284** [comment]
ah, my bad.
thanks lol

**Comment by aabi007k-hue** [comment]
{ import = "nvchad.blink.lazyspec" }

**Comment by siduck** [comment]
> ```
>                                                 { import = "nvchad.blink.lazyspec" }
> ```

🔥

**Comment by aabi007k-hue** [comment]
{ import = "nvchad.blink.lazyspec" }
