### ISSUE TITLE
How to navigate between the tabs?

### ISSUE THREAD

**Issue by Himujjal** [siduck76/neovim-dots#5]
`:tabprevious` `:tabnext` don't work. any idea how to navigate between the tabs?

**Comment by siduck76** [comment]
I use my mouse for it , I'll add the mappings for tab switching soon.

**Comment by Himujjal** [comment]
if you add the bindings, please keep it `<leader><s-k>` and `<leader><s-j>` which kind of match the vimium chrome extension tab switching. BTW, your config is great for a base configuration. I have made some changes and will soon make a pull request. If you think its worth it do merge it.

**Comment by siduck76** [comment]
My config is still basic , and yes PR's are always welcomed :)
