### ISSUE TITLE
Multiple Install Errors

### ISSUE THREAD

**Issue by marvelman3284** [siduck76/neovim-dots#8]
Whilst trying to copy this config I have run into some errors. I have tried both manually and using `install.sh`, all of these error messages will be from running the `install.sh` file. 
My first error is:
```sh
~~~~~ Linking config
find: unknown predicate `-E'
```
Next:
```sh
~~~~~ Installing plugins
Error detected while processing command line:
E492: Not an editor command: PackerInstallError detected while processing command line:
E492: Not an editor command: TSUpdate
```

## Replication
Clone this repo
cd into the folder
run `./install.sh`

## Other Information
Besides these two errors every other operation ran without errors.
I am using [neovim-nightly-bin from the aur](https://aur.archlinux.org/packages/neovim-nightly-bin/) and I have also tried [neovim-nightly-git from the aur](https://aur.archlinux.org/packages/neovim-nightly-git/) which also returns with the same results.
Installing packer on its own _also_ return the error that `PackerInstall is not an Editor Command`.

### System Information
![image](https://user-images.githubusercontent.com/58921302/112680346-a78e3580-8e43-11eb-9412-54ea433da0d6.png)

If you need any other information let me know, 
Thanks in advance for the help!

**Comment by siduck76** [comment]
@jack0son

**Comment by siduck76** [comment]
@jack0son has made the script , Im pretty bad at it , however the script has been updated . Run it ( while being in the repo's folder dir ) and once its done open neovim and type :PackerInstall .

**Comment by jack0son** [comment]
I believe this is a platform compatibility issue - have been using a mac recently and discovered it comes with a different set of shell utils than the usual GNU core utils. Several subtle differences in the APIs of find, link, etc.

I'll update this so it works on arch in the next couple days.

**Comment by marvelman3284** [comment]
> 
> 
> I believe this is a platform compatibility issue - have been using a mac recently and discovered it comes with a different set of shell utils than the usual GNU core utils. Several subtle differences in the APIs of find, link, etc.
> 
> I'll update this so it works on arch in the next couple days.

Awesome thanks for your help!

**Comment by marvelman3284** [comment]
> @jack0son has made the script , I'm not good at shell scripting, however the script has been fixed. Run it ( while being in the repo's folder dir ) and once its done open neovim and type :PackerInstall .

I tried this and the install ran without errors, but I am still getting the error that PackerInstall is not an editor command. This might  be an error with Packer

**Comment by marvelman3284** [comment]
Fixed with the updated `install.sh`
