### ISSUE TITLE
How to change the inactive window status line background

### ISSUE THREAD

**Issue by vuki656** [siduck76/neovim-dots#9]
Hey, love the config, was a big inspiration :D 

Can you please let me know how you changed the following background-color?

I've skimmed your config but couldn't find it. 

![Screenshot from 2021-03-27 19-34-04_2](https://user-images.githubusercontent.com/8104698/112731063-5eb6a980-8f35-11eb-8ff8-40d9850218cf.jpg)

**Comment by siduck76** [comment]
go to lua/statusline/lua.lua file and keep the gl.short_line_list empty , like this : 
 
 gl.short_line_list = {}

**Comment by vuki656** [comment]
> I think the inactive status line's bg color is managed by the theme , if you want to add a statusline on inactive windows , edit lua/statusline/lua.lua file and keep the gl.short_line_list empty , like this :
> 
> gl.short_line_list = {}
> 
> It will add statusline to the inactive windows as well
> 
> ![image](https://user-images.githubusercontent.com/59060246/112742324-43868100-8fab-11eb-9288-1acc28b4f9fd.png)

Got it. Thanks.
